{
 "title": "KubeVirt General - Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "VM Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kubevirt_vmi_storage_read_traffic_bytes_total) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMI by Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kubevirt_vmi_phase_count{namespace=~\".*\",phase=~\"scheduling\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "count(kubevirt_vmi_phase_count{namespace=~\".*\",phase=\"scheduled\"}) by (pod,phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "count(kubevirt_vmi_phase_count{namespace=~\".*\",phase=\"success\"}) by (pod,phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "count(kubevirt_vmi_phase_count{namespace=~\".*\",phase=\"running\"}) by (pod,phase) > 0",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "VMI by OS",
   "type": "bargauge",
   "description": "Approximate value, as some VMI can be created without the necessary annotations for OS",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(kubevirt_vmi_phase_count{namespace=~\".*\", phase=~\"running\", os!=\"<none>\"}[300s])) by (phase,os)",
     "legendFormat": "{{ os }}"
    }
   ]
  },
  {
   "title": "Allocatable Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_allocatable_nodes_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMI Running by Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(kubevirt_vmi_phase_count{namespace=~\".*\", phase=~\"running\"}[300s])) by (phase,node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "VMI by Flavor",
   "type": "gauge",
   "description": "Approximate value, as some VMI can be created without the necessary annotations for flavor",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(kubevirt_vmi_phase_count{namespace=~\".*\", phase=~\".*\", flavor!=\"<none>\"}[300s])) by (phase,flavor) > 0",
     "legendFormat": "{{ flavor }}"
    }
   ]
  },
  {
   "title": "Top Consumers of CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(rate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[1800s])) by (namespace,pod)))>0",
     "legendFormat": "{{namespace}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Top Consumers of Memory",
   "type": "timeseries",
   "description": "Namespace - VMI Name",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum (avg_over_time(kubevirt_vmi_memory_available_bytes[1800s]) - avg_over_time(kubevirt_vmi_memory_usable_bytes[1800s]))by(name, namespace)))>0",
     "legendFormat": "{{namespace}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Top Consumers of Storage IOPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_iops_read_total[1800s]) + rate(kubevirt_vmi_storage_iops_write_total[1800s])) by (namespace, name)))>0",
     "legendFormat": "{{namespace}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Top Consumers of Storage Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_read_traffic_bytes_total[1800s]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total[1800s])) by (namespace, name)))>0",
     "legendFormat": "{{namespace}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Network Traffic by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_network_receive_bytes_total[5m]) + irate(kubevirt_vmi_network_transmit_bytes_total[5m])) by (namespace, name))>0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "KubeVirt - Api Server - Read Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", instance=~\".*\", verb=~\"LIST|GET\", scope=\"cluster\"}[15m])) by (le, resource, verb))",
     "legendFormat": "{{ verb }} | {{ resource }}"
    }
   ]
  },
  {
   "title": "KubeVirt - Api Server - Write Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", instance=~\".*\", verb=~\"POST|PUT|PATCH|DELETE\"}[15m])) by (le, verb, resource)) > 0",
     "legendFormat": "{{ verb }} | {{ resource }}"
    }
   ]
  },
  {
   "title": "VMI Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_from_creation_seconds_bucket{namespace=~\".*\"}[5m])) by (phase, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}