{
 "title": "Kubevirt / API",
 "tags": [
  "kubevirt",
  "kubevirt-control-plane",
  "sig-scale"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(apiserver_request_total, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VMI Creation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_from_creation_seconds_bucket{instance=~\"$instance\"}[5m])) by (phase, le))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "VMI Phase Transition Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Pending\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Scheduling\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Scheduled\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Running\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Succeeded\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubevirt_vmi_phase_transition_time_seconds_bucket{phase=\"Failed\", instance=~\"$instance\"}[5m])) by (le,phase))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "VMI Start Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_phase_transition_time_from_creation_seconds_count{phase=\"Running\", instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Running"
    }
   ]
  },
  {
   "title": "VMI Count (approx.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kubevirt_vmi_phase_transition_time_from_creation_seconds_count{phase=\"Failed\", instance=~\"$instance\"}[20m])) by (instance)",
     "legendFormat": "{{instance}} Failed"
    },
    {
     "expr": "sum(increase(kubevirt_vmi_phase_transition_time_from_creation_seconds_count{phase=\"Running\", instance=~\"$instance\"}[20m])) by (instance)",
     "legendFormat": "{{instance}} Running"
    }
   ]
  },
  {
   "title": "Read Code - Requests",
   "type": "graph",
   "description": "How many read requests (LIST,GET,WATCH) per second do the apiservers get by code?",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\".*kubevirt.*\", instance=~\"$instance\", verb=~\"LIST|GET|WATCH\"}[5m])) by (code, group)",
     "legendFormat": "{{ code }}  {{group}} "
    }
   ]
  },
  {
   "title": "Read Request - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for reading (LIST|WATCH|GET) a given resource?",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", instance=~\"$instance\", verb=~\"LIST|GET|WATCH\", scope=\"cluster\"}[5m])) by (le, resource, verb))",
     "legendFormat": "{{ resource }} {{verb}}"
    }
   ]
  },
  {
   "title": "Write Code - Requests",
   "type": "graph",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\".*kubevirt.*\", instance=~\"$instance\", verb=~\"POST|PUT|PATCH|DELETE\"}[5m])) by (code, group)",
     "legendFormat": "{{ code }} {{group}}"
    }
   ]
  },
  {
   "title": "Write Request - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", instance=~\"$instance\", verb=~\"POST|PUT|PATCH|DELETE\"}[5m])) by (le, verb, resource))",
     "legendFormat": "{{ resource }} {{verb}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_workqueue_adds_total{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_workqueue_depth{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubevirt_workqueue_queue_duration_seconds_bucket{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Work Queue Retry Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_workqueue_retries_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unfinished Work",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kubevirt_workqueue_unfinished_work_seconds{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Longest Running Processor",
   "type": "graph",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_workqueue_longest_running_processor_seconds{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\".*kubevirt.*\", instance=~\"$instance\"}) by (instance, container)",
     "legendFormat": "{{container}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (instance, container)",
     "legendFormat": "{{container}} {{instance}} "
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_open_fds{container!=\"\"}[10m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (node, pod) +\nsum(rate(container_network_transmit_bytes_total{namespace=~\".*kubevirt.*\", instance=~\"$instance\"}[5m])) by (node, pod)",
     "legendFormat": "{{pod}} {{node}}"
    }
   ]
  },
  {
   "title": "GC Duration Mean",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{}[10m])) by (container) / sum(rate(go_gc_duration_seconds_count{}[10m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\".*kubevirt.*\", instance=~\"$instance\"}",
     "legendFormat": "{{container}} {{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_threads{container!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Etcd RPC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_type=\"unary\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_type=\"unary\", grpc_code!=\"OK\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "RCP Failed Rate"
    }
   ]
  },
  {
   "title": "90th %ile all Etcd Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "Request Duration {{instance}} "
    }
   ]
  },
  {
   "title": "Etcd DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_db_total_size_in_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{metrics_path=\"/metrics\", instance=~\"$instance\"}[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total{metrics_path=\"/metrics\", instance=~\"$instance\"}[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Rest Rate Limiter Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rest_client_rate_limiter_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (container, le, url))",
     "legendFormat": "{{container}} {{url}}"
    }
   ]
  }
 ]
}