{
 "title": "KubeVirt / Infrastructure Resources / Top Consumers",
 "tags": [ "kubevirt-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "period", "label": "interval", "query": "5m,1h,2h,4h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Top Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Memory Swap Traffic Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_memory_swap_in_traffic_bytes_total[$period]) + rate(kubevirt_vmi_memory_swap_out_traffic_bytes_total[$period])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top vCPU Wait Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_vcpu_wait_seconds[$period])) by (namespace, name))) >0"
    }
   ]
  },
  {
   "title": "Top VM Container CPU Usage Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[$period])) by (namespace,pod)))>0"
    }
   ]
  },
  {
   "title": "Top Network Traffic Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_network_receive_bytes_total[$period]) + rate(kubevirt_vmi_network_transmit_bytes_total[$period])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Storage Traffic Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_read_traffic_bytes_total[$period]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total[$period])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Storage IOPS Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_iops_read_total[$period]) + rate(kubevirt_vmi_storage_iops_write_total[$period])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Memory Used Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(container_memory_working_set_bytes{pod=~'virt-launcher-.*', container='compute'}[$period])) by (namespace, pod)))>0"
    }
   ]
  },
  { "title": "Top Consumers (over time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Swap Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_memory_swap_in_traffic_bytes_total{}[$__rate_interval]) + irate(kubevirt_vmi_memory_swap_out_traffic_bytes_total{}[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "vCPU Wait Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_vcpu_wait_seconds{}[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "VM Container CPU Usage Consumers by Pod Name (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[$__rate_interval])) by (pod, namespace))>0",
     "legendFormat": "{{pod}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Network Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_network_receive_bytes_total[$__rate_interval]) + irate(kubevirt_vmi_network_transmit_bytes_total[$__rate_interval])) by (namespace, name))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Storage Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_storage_read_traffic_bytes_total[$__rate_interval]) + irate(kubevirt_vmi_storage_write_traffic_bytes_total[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IOPS Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_storage_iops_read_total[$__rate_interval])+ irate(kubevirt_vmi_storage_iops_write_total[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_memory_working_set_bytes{pod=~'virt-launcher-.*', container='compute'}[$__rate_interval])) by (namespace, pod))>0",
     "legendFormat": "{{pod}} / {{namespace}}"
    }
   ]
  }
 ]
}