from os import listdir

autogen = """<!--
    This is an auto-generated file.
    PLEASE DO NOT EDIT THIS FILE.
    run:
        python automation/generate_pages_index.py
    to re-generate it
-->
"""
title = "# KubeVirt Runbooks\n\n"
description = "[Runbooks](https://en.wikipedia.org/wiki/Runbook) " \
              "for alerts shipped with the KubeVirt stack are located in this directory.\n\n"
example = "Examples of runbooks can be found in this repository and in the [prometheus-operator/kube-prometheus]" \
          "(https://github.com/prometheus-operator/kube-prometheus/wiki/Runbooks) repository.\n\n"
list_title = "## List of Runbooks\n"
opening = autogen + title + description + example + list_title

files = list(filter(lambda f: f.endswith(".md") and f != "README.md", listdir("docs/runbooks")))
lines = list(map(lambda f: f"* [{f[:-3]}]({f})\n", files))
lines.sort()

with open("docs/runbooks/README.md", 'w') as output:
    output.write(opening)
    for line in lines:
        output.write(line)
