# This is a basic workflow to help you get started with Actions

name: Sanity Check

# Controls when the action will run.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Generate Index for Pages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check changed files
      run: |
        for file in $(git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA}); do
          if [[ $file == "automation/generate_pages_index.py" ]] || [[ $file == docs/runbooks/* ]]; then
            FOUND=true
          fi
        done
        if [[ -z $FOUND ]]; then
          exit 0
        fi

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: generate the index file
      run: |
        make runbooks-index

    - name: validate
      run: |
        git diff --exit-code
